import {Bricolage_Grotesque}  from "next/font/google";
import "./globals.css";

const BricolageGrotesqueFonts = Bricolage_Grotesque(
  {
    weight:'400',
  }
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={BricolageGrotesqueFonts.className}
      >
        {children}
      </body>
    </html>
  );
}
